source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire' 
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka'
pod 'SAWaveToast', :git => 'https://github.com/szk-atmosphere/SAWaveToast'
pod 'IBAnimatable', :git => 'https://github.com/JakeLin/IBAnimatable'
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper'
pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper'
pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift'
pod 'JSONWebToken', :git => 'https://github.com/kylef/JSONWebToken.swift'